# Homebrew formula for `coord`. Auto-generated by scripts/release-formula.sh
# from each tagged release. Do not hand-edit.
#
# Install via the tap:
#   brew tap dmarshaltu/coord
#   brew install coord
class Coord < Formula
  desc "Local coordinator for parallel AI coding agents (MCP + A2A, atomic claims)"
  homepage "https://github.com/DmarshalTU/coord"
  license "MIT"
  version "0.3.0"

  # Pre-built binaries: Apple Silicon macOS and x86_64 Linux. On other
  # architectures, install from source:
  #   cargo install --git https://github.com/DmarshalTU/coord
  on_macos do
    on_arm do
      url "https://github.com/DmarshalTU/coord/releases/download/v#{version}/coord-aarch64-apple-darwin"
      sha256 "8de3a171edc587f9545a13505df25314f4a771633d7b2c6d797eb5aaae4145e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DmarshalTU/coord/releases/download/v#{version}/coord-x86_64-unknown-linux-gnu"
      sha256 "214ee603a8560d9494054a5745c684b392ab64b45ed82a1e5f50de302d10878e"
    end
  end

  def install
    bin.install Dir["coord-*"].first => "coord"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/coord version")
  end
end
