//! MCP bridge — exposes coord's coordination primitives as MCP tools so
//! IDE clients (Claude Code, Cursor, Codex, ...) can call them natively
//! over stdio.
//!
//! Architecture:
//!   IDE  <--stdio MCP-->  `coord mcp`  <--HTTP JSON-RPC-->  `coord serve`
//!
//! The bridge is deliberately stateless: it translates each MCP tool
//! call into the corresponding JSON-RPC method and returns the body.
//! The daemon stays long-lived; IDEs spawn short-lived bridge processes
//! per session.

use anyhow::Result;
use reqwest::Client as Http;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{
    CallToolResult, Content, Implementation, ProtocolVersion, ServerCapabilities, ServerInfo,
};
use rmcp::schemars::JsonSchema;
use rmcp::transport::stdio;
use rmcp::{tool, tool_handler, tool_router, ErrorData as McpError, ServerHandler, ServiceExt};
use serde::Deserialize;
use serde_json::{json, Value};

#[derive(Clone)]
pub struct Bridge {
    pub url: String,
    pub http: Http,
    /// Storage slot the `#[tool_handler]` macro reads to dispatch calls.
    /// Populated by `Bridge::tool_router()` (generated by `#[tool_router]`).
    tool_router: ToolRouter<Self>,
}

impl Bridge {
    pub fn new(url: String) -> Self {
        Self {
            url,
            http: Http::new(),
            tool_router: Self::tool_router(),
        }
    }

    pub async fn run(self) -> Result<()> {
        let service = self.serve(stdio()).await?;
        service.waiting().await?;
        Ok(())
    }

    /// Translate one JSON-RPC call into a `CallToolResult` containing the
    /// pretty-printed JSON body. We surface daemon errors as MCP tool
    /// errors so the agent sees them clearly instead of silently failing.
    async fn call(&self, method: &str, params: Value) -> Result<CallToolResult, McpError> {
        let body = json!({ "jsonrpc": "2.0", "id": 1, "method": method, "params": params });
        let resp = self
            .http
            .post(&self.url)
            .json(&body)
            .send()
            .await
            .map_err(|e| McpError::internal_error(format!("coord unreachable: {e}"), None))?;
        let value: Value = resp
            .json()
            .await
            .map_err(|e| McpError::internal_error(format!("decode: {e}"), None))?;
        if let Some(err) = value.get("error").and_then(|v| v.as_object()) {
            let msg = err
                .get("message")
                .and_then(|v| v.as_str())
                .unwrap_or("coord error");
            return Err(McpError::internal_error(
                msg.to_string(),
                Some(value.clone()),
            ));
        }
        let result = value.get("result").cloned().unwrap_or(Value::Null);
        let text = serde_json::to_string_pretty(&result).unwrap_or_else(|_| result.to_string());
        Ok(CallToolResult::success(vec![Content::text(text)]))
    }
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct TaskSendArgs {
    /// Human-readable task name (free-form; agents filter on this).
    pub name: String,
    /// Optional category. Common values: task, bug, feature, decision, ack,
    /// knowledge, build. Other agents can filter on this.
    #[serde(default)]
    pub kind: Option<String>,
    /// Optional priority: low, normal, high, urgent. Default: normal.
    #[serde(default)]
    pub priority: Option<String>,
    /// Optional JSON payload to attach to the task.
    #[serde(default)]
    pub payload: Option<Value>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct IdArgs {
    /// UUID of the task.
    pub id: String,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct ClaimArgs {
    /// UUID of the task to claim.
    pub id: String,
    /// The agent ID claiming the task. Must match an id from `agents/heartbeat`.
    pub agent_id: String,
    /// Optional lease length in seconds. Defaults to 300 (5 minutes).
    /// Capped at 3600. Extend before this elapses with `tasks_extend`
    /// or the task will auto-reclaim back to `pending` for someone
    /// else to pick up.
    #[serde(default)]
    pub lease_seconds: Option<u64>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct ExtendArgs {
    /// UUID of the task to extend.
    pub id: String,
    /// Agent ID currently holding the claim. Only the current claimer
    /// can extend.
    pub agent_id: String,
    /// Optional new lease length in seconds. Defaults to 300.
    #[serde(default)]
    pub lease_seconds: Option<u64>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct CompleteArgs {
    /// UUID of the task to complete.
    pub id: String,
    /// JSON result to record on the task.
    #[serde(default)]
    pub result: Option<Value>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct HeartbeatArgs {
    /// Stable agent identifier (e.g. `cursor-window-1`).
    pub id: String,
    /// Display name for the agent.
    pub name: String,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct ListArgs {
    /// Max number of tasks to return. Default 50.
    #[serde(default)]
    pub limit: Option<u64>,
    /// Optional filter by kind (e.g. "bug", "feature", "decision").
    #[serde(default)]
    pub kind: Option<String>,
    /// Optional filter by priority (e.g. "high", "urgent").
    #[serde(default)]
    pub priority: Option<String>,
    /// Optional filter by state (e.g. "pending", "claimed", "completed").
    #[serde(default)]
    pub state: Option<String>,
    /// If set and the initial result is empty, the server holds the
    /// connection open up to this many milliseconds and returns the
    /// instant a matching task lands. Capped at 60_000 server-side.
    /// Use this to turn `tasks_list` into a watch primitive — much
    /// cheaper than re-polling every 2 seconds.
    #[serde(default)]
    pub wait_ms: Option<u64>,
}

#[tool_router]
impl Bridge {
    #[tool(
        description = "Create a new task. Set kind to one of: task (default), bug, feature, \
            decision, ack, knowledge, build. Set priority to: low, normal (default), high, urgent. \
            Other agents can filter on these fields. Returns the task object including its UUID."
    )]
    async fn tasks_send(
        &self,
        Parameters(a): Parameters<TaskSendArgs>,
    ) -> Result<CallToolResult, McpError> {
        self.call(
            "tasks/send",
            json!({
                "name": a.name,
                "kind": a.kind,
                "priority": a.priority,
                "payload": a.payload,
            }),
        )
        .await
    }

    #[tool(description = "Get the current state of a task by UUID.")]
    async fn tasks_get(
        &self,
        Parameters(a): Parameters<IdArgs>,
    ) -> Result<CallToolResult, McpError> {
        self.call("tasks/get", json!({ "id": a.id })).await
    }

    #[tool(
        description = "List tasks with optional filters and optional long-poll. Filters \
            (kind, priority, state) are applied in SQL so you get matching rows up to \
            limit, not the most-recent N rows re-filtered in memory. Set wait_ms > 0 to \
            block until a matching task lands — this is how you watch for something \
            without polling. Returns an empty array on timeout."
    )]
    async fn tasks_list(
        &self,
        Parameters(a): Parameters<ListArgs>,
    ) -> Result<CallToolResult, McpError> {
        let limit = a.limit.unwrap_or(50);
        self.call(
            "tasks/list",
            json!({
                "limit": limit,
                "kind": a.kind,
                "priority": a.priority,
                "state": a.state,
                "wait_ms": a.wait_ms,
            }),
        )
        .await
    }

    #[tool(description = "Atomically claim a pending task as `agent_id` and acquire a \
            lease. The task auto-reclaims back to `pending` if you don't `tasks_complete` \
            or `tasks_extend` before the lease expires (default 5 minutes). Errors with \
            'task is not claimable' if another agent already claimed it — that is the \
            expected race signal.")]
    async fn tasks_claim(
        &self,
        Parameters(a): Parameters<ClaimArgs>,
    ) -> Result<CallToolResult, McpError> {
        self.call(
            "tasks/claim",
            json!({
                "id": a.id,
                "agentId": a.agent_id,
                "leaseSeconds": a.lease_seconds,
            }),
        )
        .await
    }

    #[tool(description = "Push the lease forward on a task you currently hold the claim \
            on. Call this on a timer (e.g. every minute) for long-running work, or just \
            before each meaningful step. Only the current claimer can extend; errors \
            'lease cannot be extended' if the task was reclaimed, cancelled, or \
            completed.")]
    async fn tasks_extend(
        &self,
        Parameters(a): Parameters<ExtendArgs>,
    ) -> Result<CallToolResult, McpError> {
        self.call(
            "tasks/extend",
            json!({
                "id": a.id,
                "agentId": a.agent_id,
                "leaseSeconds": a.lease_seconds,
            }),
        )
        .await
    }

    #[tool(description = "Sweep expired claims back to `pending` so another agent can \
            pick them up. Usually called by the daemon's background ticker; expose it \
            here in case an operator wants to force the sweep. Returns the list of \
            reclaimed tasks.")]
    async fn tasks_reclaim(&self) -> Result<CallToolResult, McpError> {
        self.call("tasks/reclaim", json!({})).await
    }

    #[tool(description = "Mark a claimed task as completed and record an optional JSON result.")]
    async fn tasks_complete(
        &self,
        Parameters(a): Parameters<CompleteArgs>,
    ) -> Result<CallToolResult, McpError> {
        self.call("tasks/complete", json!({ "id": a.id, "result": a.result }))
            .await
    }

    #[tool(description = "Cancel a task by UUID.")]
    async fn tasks_cancel(
        &self,
        Parameters(a): Parameters<IdArgs>,
    ) -> Result<CallToolResult, McpError> {
        self.call("tasks/cancel", json!({ "id": a.id })).await
    }

    #[tool(
        description = "Register or refresh an agent's presence. Call periodically (e.g. every 5s) so other agents can see you're alive."
    )]
    async fn agents_heartbeat(
        &self,
        Parameters(a): Parameters<HeartbeatArgs>,
    ) -> Result<CallToolResult, McpError> {
        self.call("agents/heartbeat", json!({ "id": a.id, "name": a.name }))
            .await
    }

    #[tool(description = "List all known agents and when they were last seen.")]
    async fn agents_list(&self) -> Result<CallToolResult, McpError> {
        self.call("agents/list", json!({})).await
    }
}

#[tool_handler]
impl ServerHandler for Bridge {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::default(),
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation {
                name: "coord".into(),
                version: env!("CARGO_PKG_VERSION").into(),
                ..Default::default()
            },
            instructions: Some(
                "Coordinate multi-agent work via coord: claim tasks atomically, heartbeat \
                 presence, and broadcast acks across Cursor / Claude Code / Codex sessions."
                    .into(),
            ),
        }
    }
}
