#!/usr/bin/env bash
# Regenerate Formula/coord.rb for a published GitHub release.
#
# Usage:
#   ./scripts/release-formula.sh v0.3.0 [output-path]
#
# Pulls SHA256SUMS from the release and writes a fresh formula. The
# output path defaults to Formula/coord.rb (relative to the current
# working directory). Idempotent: works whether the file already
# exists, has placeholders, or already has SHAs from a previous tag.

set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo "usage: $0 <vX.Y.Z> [output-path]" >&2
    exit 1
fi

VERSION="${1#v}"
TAG="v${VERSION}"
REPO="DmarshalTU/coord"
FORMULA="${2:-Formula/coord.rb}"

echo "==> Fetching SHA256SUMS for ${TAG} from ${REPO}"
SUMS="$(curl -fsSL "https://github.com/${REPO}/releases/download/${TAG}/SHA256SUMS")"

extract() {
    local target="$1"
    echo "${SUMS}" | awk -v t="coord-${target}" '$2==t {print $1}'
}

AARCH64_DARWIN="$(extract aarch64-apple-darwin)"
X86_64_LINUX="$(extract x86_64-unknown-linux-gnu)"

for v in "$AARCH64_DARWIN" "$X86_64_LINUX"; do
    if [[ -z "$v" ]]; then
        echo "FATAL: missing one or more checksums in SHA256SUMS" >&2
        echo "${SUMS}" >&2
        exit 1
    fi
done

echo "==> Writing ${FORMULA}"
mkdir -p "$(dirname "${FORMULA}")"
cat > "${FORMULA}" <<EOF
# Homebrew formula for \`coord\`. Auto-generated by scripts/release-formula.sh
# from each tagged release. Do not hand-edit.
#
# Install via the tap:
#   brew tap dmarshaltu/coord
#   brew install coord
class Coord < Formula
  desc "Local coordinator for parallel AI coding agents (MCP + A2A, atomic claims)"
  homepage "https://github.com/${REPO}"
  license "MIT"
  version "${VERSION}"

  # Pre-built binaries: Apple Silicon macOS and x86_64 Linux. On other
  # architectures, install from source:
  #   cargo install --git https://github.com/${REPO}
  on_macos do
    on_arm do
      url "https://github.com/${REPO}/releases/download/v#{version}/coord-aarch64-apple-darwin"
      sha256 "${AARCH64_DARWIN}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/${REPO}/releases/download/v#{version}/coord-x86_64-unknown-linux-gnu"
      sha256 "${X86_64_LINUX}"
    end
  end

  def install
    bin.install Dir["coord-*"].first => "coord"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/coord version")
  end
end
EOF

echo "==> Done. Review with:  git diff ${FORMULA}"
